image: rust:1.76

stages:
  - build
  - lint
  - deploy

build-job:
  stage: build
  image: rust
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/rusters

lint-job:
  stage: lint
  image: rust
  script:
    - rustup component add clippy
    - cargo clippy

azure:
  stage: deploy
  script:
    - bash ./deploy-aks.sh
